FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY Directory.Build.props .
COPY src/Gazetteer.Core/Gazetteer.Core.csproj src/Gazetteer.Core/
COPY src/Gazetteer.Web/Gazetteer.Web.csproj src/Gazetteer.Web/
RUN dotnet restore src/Gazetteer.Web/Gazetteer.Web.csproj

COPY src/ src/
RUN dotnet publish src/Gazetteer.Web/Gazetteer.Web.csproj -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Gazetteer.Web.dll"]
